#!/bin/sh

start_node() {
    if test -f "node_modules";
    then
        if ! command -v yarn &> /dev/null
        then
            NODE_HELPER="npm"
            npx melon $@
        else
            yarn melon $@
        fi
    else
        if ! command -v yarn &> /dev/null
        then
            NODE_HELPER="npm"
            npm i
            npx melon $@
        else
            yarn
            yarn melon $@
        fi
    fi
}



run() {
    if command -v "node" > /dev/null;
    then
        mkdir .dotbuild >/dev/null 2>&1
        echo "$@" > .dotbuild/command

        case $1 in
            rebuild)
                echo Rebuilding...
                build
            ;;

            doctor)
                if [ -z $2 ]; then 
                    echo "You must specify the doctor name. See scripts/doctors for more information."; 
                else 
                    run_doctor $2
                fi
            ;;

            *)
                start_node $@
                exit $?
            ;;
        esac
    else
        if [ -n "$MOZILLABUILD" ]; then
            PATH="$PATH:/c/Program Files/nodejs"
            run $@
        else
            echo "This melon command requires node, which wasn't found on the system!"
            exit 1
        fi
    fi
}

run $@